services:
  pico-container:
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: always
    network_mode: host
    container_name: pico_container
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: Asia/Shanghai
    volumes:
      - "/Users/alex/dev/opensource/picoquic:/home/dev/picoquic"
